# Window information
WINDOWWIDTH = 600
WINDOWHEIGHT = 400

BORDER = 10
DOTLINESIZE = 10
LINEGAP = 5

# Field borders
BORDERB = WINDOWHEIGHT - BORDER
BORDERT = BORDER
BORDERL = BORDER
BORDERR = WINDOWWIDTH - BORDER

# Misc
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

FRAMERATE = 60

# Paddle
PMOVESPEED = 6
PADDLEWIDTH = 16
PADDLEHEIGHT = 64

PADDLEINDENT = 10

# Movement directions (down, no movement, up)
MDOWN = 1
MNO = 0
MUP = -1

# Ball - incl. spawn limits (for x co-ord)
BALLSIZE = 8
LEFTX_SPAWN_LIM = (WINDOWWIDTH / 2) - 100
RIGHTX_SPAWN_LIM = (WINDOWWIDTH / 2) + 100
TOPY_SPAWN_LIM = BORDERT + (BALLSIZE / 2)
BOTY_SPAWN_LIM = BORDERB - (BALLSIZE / 2)

# Score locations
P1SCORELOC = (275, 30)
P2SCORELOC = (323, 30)